### ISSUE TITLE
-u option missing

### ISSUE THREAD

**Issue by bapt** [mpieuchot/ctfdump#5]
for this version of ctfdump to be a complete drop-in replacement for CDDL's ctfdump it is missing the -u file option. This option might be useful for debugging

**Comment by mpieuchot** [comment]
I didn't intend to write a complete drop-in replacement.  With that in mind I didn't implement "-u" because I don't see a use for it.

Now if somebody wants this feature, can explain why it is useful and come with a diff, sure why not.
